fmsApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('login',auth_views.LoginView.as_view(template_name="login.html",redirect_authenticated_user = True),name='login'),
    path('userlogin', views.login_user, name="login-user"),
    path('user-register', views.registerUser, name="register-user"),
    path('logout',views.logoutuser,name='logout'),
    path('profile',views.profile,name='profile'),
    path('update-profile',views.update_profile,name='update-profile'),
    # path('update-avatar',views.update_avatar,name='update-avatar'),
    path('update-password',views.update_password,name='update-password'),
    path('', views.home, name='home-page'),
    path('my_posts', views.posts_mgt, name='posts-page'),
    path('manage_post', views.manage_post, name='manage-post'),
    path('manage_post/<int:pk>', views.manage_post, name='manage-post'),
    path('save_post', views.save_post, name='save-post'),
    path('delet_post', views.delete_post, name='delete-post'),
    path(r'shareF/<str:id>', views.shareF, name='share-file-id'),
    path('shareF/', views.shareF, name='share-file'),
]

fms_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fmsApp.urls')),
    path('', include('user_app.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from user_app.views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin_register', index, name='register'),
    path('user-login', user_login, name='user-login'),
    path('dashboard', dashboard, name='dashboard'),
    path('logout',logout, name='logout'),
    path('upload_file',upload_file, name='upload_file'),

    path('admin_panel_view_users/', admin_panel_view_users, name="admin_panel_view_users"),
    path('admin_panel_search_user/', admin_panel_search_user, name='admin_panel_search_user'),
    path('admin_panel_delete_user/',admin_panel_delete_user, name='admin_panel_delete_user'),
    path('admin_panel_view_active_user/', admin_panel_view_active_user, name="admin_panel_view_active_user"),
    path('admin_panel_search_active_user/', admin_panel_search_active_user, name="admin_panel_search_active_user"),
    path('admin_panel_delete_active_user/', admin_panel_delete_active_user, name="admin_panel_delete_active_user"),
    path('admin_panel_view_inactive_user/', admin_panel_view_inactive_user, name="admin_panel_view_inactive_user"),
    path('admin_panel_search_inactive_user/', admin_panel_search_inactive_user, name="admin_panel_search_inactive_user"),
    path('admin_panel_block_user/', admin_panel_block_user, name="admin_panel_block_user"),


    # password reset/forget password URL
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="reset_password"),
    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
    name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
    name="password_reset_confirm"),
    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
    name="password_reset_complete"),

]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from user_app.constant import create_slug
# Create your models here.

class Folder(models.Model):
    name = models.CharField(max_length=255)
    is_secret = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

class FolderData(models.Model):
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    name =  models.CharField(max_length=255)
    is_secret = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, null=True, blank=True, unique=True)
    file_docs = models.FileField(upload_to='FolderData/docs', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            slugs = list(FolderData.objects.all().values_list('slug', flat=True))
            self.slug = create_slug(name=self.name, slugs=slugs)
        super(FolderData, self).save(*args, **kwargs)

class FolderDataAccess(models.Model):
    folder_data = models.ForeignKey(FolderData, on_delete=models.CASCADE)
    users = models.ManyToManyField(User, blank=True, related_name='folderdataaccess_users')


class FriendList(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User, blank=True, related_name='friendlist_friends')

class FriendRequest(models.Model):
    STATUS_CHOICES = [
        ('pending', 'pending'),
        ('accepted', 'accepted'),
        ('rejected','rejected'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friendrequest_owner')
    friend = models.ForeignKey(User, on_delete=models.CASCADE)
    friend_status = models.CharField(max_length=255, choices=STATUS_CHOICES)


class OwnerPin(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    pin_code = models.CharField(max_length=10)

fmsApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm, UserChangeForm

from django.contrib.auth.models import User
from .models import Post

class UserRegistration(UserCreationForm):
    email = forms.EmailField(max_length=250,help_text="The email field is required.")
    first_name = forms.CharField(max_length=250,help_text="The First Name field is required.")
    last_name = forms.CharField(max_length=250,help_text="The Last Name field is required.")

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', 'first_name', 'last_name')
    

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            user = User.objects.get(email = email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"The {user.email} mail is already exists/taken")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username = username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"The {user.username} mail is already exists/taken")


class UpdateProfile(UserChangeForm):
    username = forms.CharField(max_length=250,help_text="The Username field is required.")
    email = forms.EmailField(max_length=250,help_text="The Email field is required.")
    first_name = forms.CharField(max_length=250,help_text="The First Name field is required.")
    last_name = forms.CharField(max_length=250,help_text="The Last Name field is required.")
    current_password = forms.CharField(max_length=250)

    class Meta:
        model = User
        fields = ('email', 'username','first_name', 'last_name')

    def clean_current_password(self):
        if not self.instance.check_password(self.cleaned_data['current_password']):
            raise forms.ValidationError(f"Password is Incorrect")

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            user = User.objects.exclude(id=self.cleaned_data['id']).get(email = email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"The {user.email} mail is already exists/taken")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.exclude(id=self.cleaned_data['id']).get(username = username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"The {user.username} mail is already exists/taken")

class UpdatePasswords(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm rounded-0'}), label="Old Password")
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm rounded-0'}), label="New Password")
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm rounded-0'}), label="Confirm New Password")
    class Meta:
        model = User
        fields = ('old_password','new_password1', 'new_password2')

class SavePost(forms.ModelForm):
    user = forms.IntegerField(help_text = "User Field is required.")
    title = forms.CharField(max_length=250,help_text = "Title Field is required.")
    description = forms.Textarea()

    class Meta:
        model= Post
        fields = ('user','title','description','file_path')
    
    def clean_title(self):
        id = self.instance.id if not self.instance == None else 0
        try:
            if id.isnumeric():
                 post = Post.objects.exclude(id = id).get(title = self.cleaned_data['title'])
            else:
                 post = Post.objects.get(title = self.cleaned_data['title'])
        except:
            return self.cleaned_data['title']
        raise forms.ValidationError(f'{post.title} post Already Exists.')

    def clean_user(self):
        user_id = self.cleaned_data['user']
        print("USER: "+ str(user_id))
        try:
            user = User.objects.get(id = user_id)
            return user
        except:
            raise forms.ValidationError("User ID is unrecognize.")

user_app/forms.py
from django import forms
from django.contrib.auth import authenticate    
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class LoginForm(forms.Form):
    email = forms.CharField(max_length=255,required=True, widget=forms.TextInput(attrs={'class':'form-control','placeholder':'enter email', 'required':'true', 'autocomplete':'off'}))
    password = forms.CharField(required=True,  widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'***********', 'required':'true', 'autocomplete':'off', 'aria-describedby':'password-addon'}))

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        check_user = User.objects.filter(email=email).first()
        if not check_user:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        print('*******************', check_user.username)
        user = authenticate(username=check_user.username, password=password)

        if not user:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = User.objects.filter(email=email).first()

        if not user:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        user = authenticate(username=user.username, password=password)
        return user


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name', 'autocomplete': 'off'}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name', 'autocomplete': 'off'}))
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email', 'autocomplete': 'off'}))
    password1 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password', 'autocomplete': 'off'}))
    password2 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm password', 'autocomplete': 'off'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email address is already in use.')
        return email

    def clean_password2(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('The two password fields did not match.')
        return password2


    def save(self, commit=True):
        user = super().save(commit=False)
        username = self.cleaned_data.get('email').split('@')[0]
        user.username = username
        if commit:
            user.save()
        return user

user_app/templates/accounts/password_change.html
{% extends 'adminpanel/base.html'%}


{% block title %}
Change Password
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar.html'%}
{% if user.is_authenticated %}
{% include 'adminpanel/partial/leftnavbar.html' %}
{% endif %}


<div class="loader_bg">
  <div class="loader"></div>
</div>


<div class="account-pages my-2 pt-sm-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="text-center mb-5 text-muted">
          <a href="index.html" class="d-block auth-logo">
            <img src="assets/images/logo-dark.png" alt="" height="20" class="auth-logo-dark mx-auto">
            <img src="assets/images/logo-light.png" alt="" height="20" class="auth-logo-light mx-auto">
          </a>

        </div>
      </div>
    </div>
    <!-- end row -->
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-5">
        <div class="card">

          <div class="card-body">

            <div class="p-2">


              <div class="avatar-md mx-auto">
                <div class="avatar-title rounded-circle bg-light">
                  <i class="fa fa-key h1 mb-0 text-success"></i>
                </div>
              </div>
              <div class="p-2 mt-4">
                <h4 class="text-success">Change Password</h4>

                <div class="mt-4">
                  <form method="post">
                    {% csrf_token %}

                    {% for field in form %}
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    {% endfor %}

                    <div class="mb-3">
                      <label class="form-label">Old Password</label>
                      <div class="input-group auth-pass-inputgroup">
                        <input type="password" name="old_password" class="form-control" placeholder="Old password"
                          aria-label="Password" aria-describedby="password-addon" id="id_old_password" required="true" autocomplete="off">
                        <button class="btn btn-light password-addon" type="button" ><i
                            class="mdi mdi-eye-outline"></i></button>
                      </div>
                    </div>

                    <div class="mb-3">
                      <label class="form-label">New Password</label>
                      <div class="input-group auth-pass-inputgroup">
                        <input type="password" name="new_password1" class="form-control" placeholder="New password"
                          aria-label="Password" aria-describedby="password-addon" id="id_new_password1" required="true" autocomplete="off">
                        <button class="btn btn-light password-addon" type="button" ><i
                            class="mdi mdi-eye-outline"></i></button>
                      </div>
                    </div>

                    <div class="mb-3">
                      <label class="form-label">Confirm Password</label>
                      <div class="input-group auth-pass-inputgroup">
                        <input type="password" name="new_password2" class="form-control" placeholder="Confirm password"
                          aria-label="Password" aria-describedby="password-addon2" id="id_new_password2" required="true" autocomplete="off">
                        <button class="btn btn-light password-addon" type="button" ><i
                            class="mdi mdi-eye-outline"></i></button>
                      </div>
                    </div>

                    <div class="text-end">
                      <button class="btn btn-success w-md waves-effect waves-light" type="submit">Change Password</button>
                    </div>

                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}

user_app/templates/accounts/password_change_done.html
{% extends 'adminpanel/base.html'%}

{% block title %}
Password Changed
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar.html'%}
{% if user.is_authenticated %}
{% include 'adminpanel/partial/leftnavbar.html' %}
{% endif %}

<div class="loader_bg">
    <div class="loader"></div>
</div>

<div class="main-content">
    <div class="page-content">
        <div class="container-fluid" id="container-div">
            <div class="row">
                <div class="col mt-5">

                    <h3 class="text-success text-center mt-5">Password change successfully</h3>

                    <p class="text-center">Your password Updated. Now you will login with new password</p>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_app/templates/accounts/password_reset.html
{% extends 'adminpanel/base.html' %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar2.html'%}

<div class="loader_bg">
    <div class="loader"></div>
</div>

<div class="account-pages my-3 pt-sm-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center mb-5 text-muted">
                    <a href="index.html" class="d-block auth-logo">
                        <img src="assets/images/logo-dark.png" alt="" height="20" class="auth-logo-dark mx-auto">
                        <img src="assets/images/logo-light.png" alt="" height="20" class="auth-logo-light mx-auto">
                    </a>

                </div>
            </div>
        </div>
        <!-- end row -->
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card">

                    <div class="card-body">

                        <div class="p-2">


                            <div class="avatar-md mx-auto">
                                <div class="avatar-title rounded-circle bg-light">
                                    <i class="fa fa-envelope h1 mb-0 text-success"></i>
                                </div>
                            </div>
                            <div class="mt-4">
                                <div class="alert alert-success text-center mb-4" role="alert">
                                    Enter your Email and instructions will be sent to you!
                                </div>
                                <form method="post">
                                    
                                    {% csrf_token %}

                                    <div class="mb-3">
                                        <label for="useremail" class="form-label">Email</label>
                                        <input type="email" class="form-control" id="useremail"
                                            placeholder="Enter email" name="email" id="id_email" required="true" autocomplete="off">

                                    </div>

                                    <div class="text-end">
                                        <button class="btn btn-success w-md waves-effect waves-light"
                                            type="submit">Reset</button>
                                    </div>

                                </form>
                                <div class="mt-5 text-center">
                                    <p><a href="{% url 'login' %}" class="fw-medium text-success"> Back To
                                            Login</a> </p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>





        {% endblock %}

user_app/templates/accounts/password_reset_done.html
{% extends 'adminpanel/base.html' %}

{% block title %}
Password Reset Done
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar2.html'%}

<div class="loader_bg">
    <div class="loader"></div>
</div>

<br><br><br>
<div class="container mt-5">
    <div class="row">
        <div class="col mt-5">
            <h3>Password reset complete</h3>

            <p>Your password has been set. You may go ahead and log in now.</p>

            <a href="{% url 'login'%}" class="btn btn-sm btn-success">Log in</a>
        </div>
    </div>
</div>
{% endblock %}

user_app/templates/accounts/password_reset_form.html
{% extends 'adminpanel/base.html'%}

{% block title %}
New Password
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar2.html'%}

<head>
    <style type="text/css">
        html {
            overflow-y: hidden;
        }
    </style>
</head>

<div class="loader_bg">
    <div class="loader"></div>
</div>

<div class="account-pages my-3 pt-sm-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center mb-5 text-muted">
                    <a href="index.html" class="d-block auth-logo">
                        <img src="assets/images/logo-dark.png" alt="" height="20" class="auth-logo-dark mx-auto">
                        <img src="assets/images/logo-light.png" alt="" height="20" class="auth-logo-light mx-auto">
                    </a>

                </div>
            </div>
        </div>
        <!-- end row -->
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card">

                    <div class="card-body">

                        <div class="p-2">


                            <div class="avatar-md mx-auto">
                                <div class="avatar-title rounded-circle bg-light">
                                    <i class="fa fa-key h1 mb-0 text-success"></i>
                                </div>
                            </div>
                            <div class="p-2 mt-4">
                                <h4 class="text-success">New Password</h4>

                                <div class="mt-4">
                                    <form method="post">
                                        {% csrf_token %}

                                    {% for field in form %}
                                    {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                    {% endfor %}

                                        <div class="mb-3">
                                            <label class="form-label">New Password</label>
                                            <div class="input-group auth-pass-inputgroup">
                                                <input type="password" name="new_password1" class="form-control"
                                                    placeholder="New password" aria-label="Password"
                                                    aria-describedby="password-addon" id="id_new_password1"
                                                    required="true" autocomplete="off">
                                                <button class="btn btn-light password-addon" type="button"><i
                                                        class="mdi mdi-eye-outline"></i></button>
                                            </div>
                                        </div>


                                        <div class="mb-3">
                                            <label class="form-label">Confirm Password</label>
                                            <div class="input-group auth-pass-inputgroup">
                                                <input type="password" name="new_password2" class="form-control"
                                                    placeholder="Confirm password" aria-label="Password"
                                                    aria-describedby="password-addon" id="id_new_password2"
                                                    required="true" autocomplete="off">
                                                <button class="btn btn-light password-addon" type="button"><i
                                                        class="mdi mdi-eye-outline"></i></button>
                                            </div>
                                        </div>


                                        <div class="text-end">
                                            <button class="btn btn-success w-md waves-effect waves-light"
                                                type="submit">Save Password</button>
                                        </div>

                                    </form>
                                </div>
                            </div>



                        </div>
                    </div>
                </div>
            </div>
        </div>





        {% endblock %}

user_app/templates/accounts/password_reset_sent.html
{% extends 'adminpanel/base.html' %}

{% block title %}
Reset Password Sent
{% endblock %}

{% block content %}
{% include 'adminpanel/partial/navbar2.html'%}

<div class="loader_bg">
    <div class="loader"></div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col mt-5">

            <h3 class="mt-5">Password reset sent</h3>

            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>

            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
                your spam folder.</p>
            
                <p>Not received email? <a href="{% url 'reset_password' %}" class="text-success">click here</a> for resend email. </p>
        </div>
    </div>
</div>
{% endblock %}